/* open partially cleaned EC13 */
/* this temp file is generated by core/ecpc/ecmerge/collapse_ecs.do */
use $tmp/ec13_precollapse_tmp.dta, clear

/* keep healthcare-related activities */
keep if inlist(nic, 861, 862, 869, 871, 872, 873, 879)

drop *shric*

/* only keep the sector, location, employment, and activity fields */
keep sector count_all emp_all gov nic ec13_state_id ec13_district_id ec13_subdistrict_id ec13_village_id ec13_town_id

save $covidpub/ec13_hosp_microdata, replace
