---
# config file for COVID forecasting site

# define globals shared across Python and Stata
globals:
    ccode: ~/ddl/covid/forecasting
    cdata: ~/iec/covid/forecasting/dev
    tileset_name: covid-forecasting-dev

# list folders with Python functions to be added to the python path for easy use
python: 
    ~/ddl/tools/py/geospatialtools

    

