channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - geos
  - geopandas=0.9
  - geotiff=1
  - git=2
  - haversine=0.4
  - matplotlib=3
  - numpy=1
  - pandas=1
  - proj=6
  - pygeos=0.8
  - pysal=2
  - rasterio=1
  - rasterstats=0.14
  - shapely=1
  - pyyaml
  - pip
  - pip:
    - topojson
